version: '3.8'

services:
    back:
        build: ./back
        ports:
          - 8080:8080
        container_name: backend
    front:
        build: ./front
        ports:
          - 5001:5001
        container_name: frontend
    redis:
        image: redis:7.0-rc
        command: redis-server
        container_name: redis-server
        