version: '3.8'

services:
    back:
        build: ./back
        ports:
          - 8080:8080
        container_name: backend
    front:
        build: ./front
        ports:
          - 5000:5000
        container_name: frontend