version: '3.8'

services:
    nginx:
        image: nginx
        restart: unless-stopped
        volumes:
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
          - 80:80
        container_name: nginx
        depends_on:
          - front
          - back
    back:
        build: ./example-backend
        container_name: back
    front:
        build: ./example-frontend
        container_name: front
    redis:
        image: redis:7.0-rc
        command: redis-server
        container_name: redis-server
    db:
        image: postgres:13.2-alpine
        restart: unless-stopped
        environment:
          POSTGRES_PASSWORD: postgres
        container_name: postgres
    adminer:
        image: adminer:4
        restart: always
        environment:
          - ADMINER_DESIGN=galkaev
        ports:
          - 8083:8080