version: '3.8'

services:
    back:
        build: ./ml-kurkkumopo-backend-master
        ports:
          - 5000:5000
        container_name: mlbackend
    front:
        build: ./ml-kurkkumopo-frontend-master
        ports:
          - 3000:3000
        container_name: mlfrontend
    training:
        build: ./ml-kurkkumopo-training-master
        container_name: mltraining